version: '2'
services:
  web:
    image: nginx:1.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      # - <%= scope['s_hosting::config_dir'] %>/certs/certificate.pem:/etc/nginx/certificate.pem:ro
      # - <%= scope['s_hosting::config_dir'] %>/certs/certificate.key:/etc/nginx/certificate.key:ro
    links:
      - uchiwa
  uchiwa:
    image: uchiwa/uchiwa:latest
    volumes:
      - ./conf/uchiwa.json:/config/config.json:ro
    links:
      - sensu
  sensu-server:
    build:
      context: .
    links:
      - redis
    depends_on:
      - redis
      # - rabbitmq
  sensu-api:
    build:
      context: .
    links:
      - redis
    depends_on:
      - redis
      # - rabbitmq
  redis:
    image: redis:3.0
  # rabbitmq:
  #   image: rabbitmq:3.6

# volumes:
#   plf_chat_test:
#     external: true
